# Generated by Django 4.2.30 on 2026-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
